name: pull-request-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies with yarn
        working-directory: ./web
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run Tests
        working-directory: ./web
        run: yarn test
